server {
    listen 80;
    listen [::]:80;

    server_name emma.realjanelove.com localhost;

    root /var/www/html;
    index index.php index.html;

    charset utf-8;

    client_max_body_size 256m;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;

        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
        fastcgi_param HTTP_PROXY "";

        fastcgi_connect_timeout 10s;
        fastcgi_send_timeout 300s;
        fastcgi_read_timeout 300s;

        fastcgi_cache WORDPRESS;

        fastcgi_cache_key "$scheme|$request_method|$host|$request_uri";

        fastcgi_cache_bypass $skip_cache;
        fastcgi_no_cache $skip_cache;

        fastcgi_no_cache $upstream_http_set_cookie;

        fastcgi_cache_valid 200 10m;
        fastcgi_cache_valid 301 302 10m;
        fastcgi_cache_valid 404 1m;

        fastcgi_cache_lock on;
        fastcgi_cache_lock_timeout 10s;

        fastcgi_cache_use_stale
            error
            timeout
            invalid_header
            updating
            http_500
            http_503;

        add_header X-FastCGI-Cache $upstream_cache_status always;
    }

    location ~* \.(?:css|js|mjs|jpg|jpeg|gif|png|webp|avif|ico|svg|woff|woff2|ttf|eot)$ {
        try_files $uri =404;

        expires 7d;
        access_log off;
        log_not_found off;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        access_log off;
        log_not_found off;
        allow all;
    }

    location = /wp-config.php {
        deny all;
    }

    location ~* ^/(?:readme\.html|license\.txt)$ {
        deny all;
    }

    location ~* /(?:uploads|files)/.*\.php$ {
        deny all;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }



    

}